development:
  adapter: postgresql
  encoding: utf8
  database: ifttt_d
  pool: 5
  host: localhost
  username: baldor
  password: baldor123

test:
  adapter: postgresql
  encoding: utf8
  database: ifttt_t
  pool: 5
  host: localhost
  username: baldor
  password: baldor123
