# config/settings.yml
defaults: &defaults
  barclay_customer_url: <%= ENV["BARCLAY_CUSTOMER_URL"] %>
  barclay_account_url: <%= ENV["BARCLAY_ACCOUNT_URL"] %>
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
